const null_books = [
    {
        id: 1,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 2,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 3,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 4,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 5,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 6,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 7,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 8,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 9,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 10,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 11,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 12,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 13,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 14,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 15,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 16,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 17,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 18,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 19,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
    {
        id: 20,
        name: "",
        discounted_price: "",
        img_url: '',
        publisher: "",
        price: 0,
        author: [],
        book_year: [],
        course: [],
        page_count: 0,
        subject: [],
    },
];
export default null_books;